fastlane_version '2.157'
default_platform :ios

platform :ios do
desc 'Builds project and executes unit tests'
lane :unit_test do |options|
    scan(
    clean: options[:clean],
    skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
end

desc 'Builds the iOS project'
lane :build do
    gym(scheme: "AnyApp") # Replace with your actual scheme name
end
end
