fastlane_version '2.157'
default_platform :ios

platform :ios do
desc 'Builds project and executes unit tests'
lane :unit_test do |options|
    scan(
    clean: options.fetch(:clean, true), # Default: clean = true
    skip_package_dependencies_resolution: options.fetch(:skip_package_dependencies_resolution, false) # Default: false
    )
end

desc 'Builds the iOS project without code signing'
lane :build do
    gym(
    scheme: "ad-hoc",
    export_method: "development",
    skip_codesigning: true,
    )
end
end
