name: Pull Request

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Build Project
        run: bundle exec fastlane build

      - name: Run tests
        run: bundle exec fastlane unit_test